import numpy as np 

##########################################################################################
##This script aim to generate the amount generated by the portfolio during the past year##
##Regarding to the distribution of each asset in the portfolio                          ##
##########################################################################################
def Distribution_Portfolio(Amount_Each_Value, DataFrame_Source) :
    #If there is a uniform repartition
    if isinstance(Amount_Each_Value, (int, float)) : 

        def Quantity(Asset_Price,Amount_Each_Value) : 
            return int(Amount_Each_Value/Asset_Price)

        DataFrame_Distribution = []
        for i in range(0,len(DataFrame_Source.iloc[0])): 
            DataFrame_Distribution.append(Quantity(DataFrame_Source.iloc[0][i],Amount_Each_Value))


        Value_Portfolio = []

        for i in range(0,len(DataFrame_Source)) : 
            Value = DataFrame_Source.iloc[i]*DataFrame_Distribution
            Value_Portfolio.append(np.sum(Value))

        DataFrame_Source["Portfolio"] = Value_Portfolio
        DataFrame = DataFrame_Source
        return DataFrame
    #If there is a non-uniform distribution
    elif isinstance(Amount_Each_Value, (list,tuple)) : 

        def Quantity(Asset_Price,Amount_Each_Value) : 
            return int(Amount_Each_Value/Asset_Price)


        DataFrame_Distribution = []
        for i in range(0,len(DataFrame_Source.iloc[0])): 
            DataFrame_Distribution.append(Quantity(DataFrame_Source.iloc[0][i],Amount_Each_Value[i]))


        Value_Portfolio = []

        for i in range(0,len(DataFrame_Source)) : 
            Value = DataFrame_Source.iloc[i]*DataFrame_Distribution
            Value_Portfolio.append(np.sum(Value))

        DataFrame_Source["Portfolio"] = Value_Portfolio
        DataFrame = DataFrame_Source
        return DataFrame



